package com.example.arclesocialapp.enumeration;

public enum CharacterTrait {
    ADAPTIVE,
    CALM,
    CAREFUL,
    CHEERFUL,
    CONFIDENT,
    COOPERATIVE,
    CREATIVE,
    CURIOUS,
    EMPATHETIC,
    ENERGETIC,
    FUNNY,
    HELPFUL,
    HUMBLE,
    INDIVIDUALISTIC,
    KIND,
    LEADING,
    OPTIMISTIC,
    ORGANIZED,
    PATIENT,
    PERFECTIONIST,
    RELIABLE,
    RESPECTFUL,
    RESPONSIBLE,
    SCRUPULOUS,
    SHY,
    SOCIABLE,
    STOIC,
    SYMPATHETIC,
    TOLERANT,
    WITTY
}
